// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmrJgvgtp1v_JDXJKtL8ZRYf8TyfTWls',
    appId: '1:789873044174:web:7860fe836f89dfb65a3e9f',
    messagingSenderId: '789873044174',
    projectId: 'weather-forecast-14f2f',
    authDomain: 'weather-forecast-14f2f.firebaseapp.com',
    storageBucket: 'weather-forecast-14f2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmvZbB4fNNtFGRfK45r7ANf8YlgV6HsIM',
    appId: '1:789873044174:android:f3e3ddbd34dfe4255a3e9f',
    messagingSenderId: '789873044174',
    projectId: 'weather-forecast-14f2f',
    storageBucket: 'weather-forecast-14f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfSzT88Zl9JHstIlOCI6OH6XHcDUr5QA',
    appId: '1:789873044174:ios:46ffc2e2d26a51055a3e9f',
    messagingSenderId: '789873044174',
    projectId: 'weather-forecast-14f2f',
    storageBucket: 'weather-forecast-14f2f.firebasestorage.app',
    iosBundleId: 'com.example.weatherForecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGfSzT88Zl9JHstIlOCI6OH6XHcDUr5QA',
    appId: '1:789873044174:ios:46ffc2e2d26a51055a3e9f',
    messagingSenderId: '789873044174',
    projectId: 'weather-forecast-14f2f',
    storageBucket: 'weather-forecast-14f2f.firebasestorage.app',
    iosBundleId: 'com.example.weatherForecast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARmrJgvgtp1v_JDXJKtL8ZRYf8TyfTWls',
    appId: '1:789873044174:web:7d6efcac40b6040f5a3e9f',
    messagingSenderId: '789873044174',
    projectId: 'weather-forecast-14f2f',
    authDomain: 'weather-forecast-14f2f.firebaseapp.com',
    storageBucket: 'weather-forecast-14f2f.firebasestorage.app',
  );
}
